import db from "../utils/databasepg";

export const insertNutrition = async (food) => {
  console.log("hello from insertNutrition");
  const {
    alcohol,
    caffiene,
    water,
    calories,
    protein,
    fats,
    carbs,
    fiber,
    starch,
    sugar,
    addedsugar,
    cystine,
    histidine,
    isoleucine,
    leucine,
    lysine,
    methionine,
    phenylalanine,
    threonine,
    tryptophan,
    tyrosine,
    valine,
    monofat,
    polyfat,
    omega3ala,
    omega3epa,
    omega3dha,
    satfat,
    transfat,
    thiamine,
    riboflavin,
    niacin,
    panto,
    pyriodox,
    combalamin,
    folate,
    vita,
    vitd,
    vite,
    vitk,
    calcium,
    copper,
    iron,
    magnesium,
    manganese,
    phosphorus,
    potassium,
    selenium,
    sodium,
    zinc,
    cholesterol,
    choline,
    vitc,
    name,
    servingqty,
    servingunit,
    servingweightgrams,
    image,
    timestamp,
  } = food;

  const query = `INSERT INTO nutrition(alcohol,
caffiene,
water,
calories,
protein,
fats,
carbs,
fiber,
starch,
sugar,
addedsugar,
cystine,
histidine,
isoleucine,
leucine,
lysine,
methionine,
phenylalanine,
threonine,
tryptophan,
tyrosine,
valine,
monofat,
polyfat,
omega3ala,
omega3epa,
omega3dha,
satfat,
transfat,
thiamine,
riboflavin,
niacin,
panto,
pyriodox,
combalamin,
folate,
vita,
vitd,
vite,
vitk,
calcium,
copper,
iron,
magnesium,
manganese,
phosphorus,
potassium,
selenium,
sodium,
zinc,
cholesterol, 
choline, 
vitc, 
name,
servingqty,
servingunit,
servingweightgrams,
image,
timestamp) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31,$32, $33, $34, $35, $36, $37, $38, $39, $40, $41, $42, $43, $44, $45, $46, $47, $48, $49, $50, $51, $52, $53, $54, $55, $56, $57, $58, $59) RETURNING *`;
  const values = [
    alcohol[0] ?? 0,
    caffiene[0] ?? 0,
    water[0] ?? 0,
    calories[0] ?? 0,
    protein[0] ?? 0,
    fats[0] ?? 0,
    carbs[0] ?? 0,
    fiber[0] ?? 0,
    starch[0] ?? 0,
    sugar[0] ?? 0,
    addedsugar[0] ?? 0,
    cystine[0] ?? 0,
    histidine[0] ?? 0,
    isoleucine[0] ?? 0,
    leucine[0] ?? 0,
    lysine[0] ?? 0,
    methionine[0] ?? 0,
    phenylalanine[0] ?? 0,
    threonine[0] ?? 0,
    tryptophan[0] ?? 0,
    tyrosine[0] ?? 0,
    valine[0] ?? 0,
    monofat[0] ?? 0,
    polyfat[0] ?? 0,
    omega3ala[0] ?? 0,
    omega3epa[0] ?? 0,
    omega3dha[0] ?? 0,
    satfat[0] ?? 0,
    transfat[0] ?? 0,
    thiamine[0] ?? 0,
    riboflavin[0] ?? 0,
    niacin[0] ?? 0,
    panto[0] ?? 0,
    pyriodox[0] ?? 0,
    combalamin[0] ?? 0,
    folate[0] ?? 0,
    vita[0] ?? 0,
    vitd[0] ?? 0,
    vite[0] ?? 0,
    vitk[0] ?? 0,
    calcium[0] ?? 0,
    copper[0] ?? 0,
    iron[0] ?? 0,
    magnesium[0] ?? 0,
    manganese[0] ?? 0,
    phosphorus[0] ?? 0,
    potassium[0] ?? 0,
    selenium[0] ?? 0,
    sodium[0] ?? 0,
    zinc[0] ?? 0,
    cholesterol[0] ?? 0,
    choline[0] ?? 0,
    vitc[0] ?? 0,
    name,
    servingqty,
    servingunit,
    servingweightgrams,
    image,
    timestamp,
  ];

  const response = await db.query(query, values);
  return response.rows[0] ?? 0;
};
